### ISSUE TITLE
Add Copyright. 

### ISSUE THREAD

**Issue by jokerz5575** [malwarepad/cavOS#14]
Hi,

In the license file you have the line 
`  <program>  Copyright (C) <year>  <name of author> `

Which is empty therefore you have no copyright claim on your project. 
I would suggest that you add your copyright information.

**Comment by malwarepad** [comment]
To my understanding, those are just instructions for anyone using the license. Even the idea of having to copy paste that onto every file is theoretically unnecessary since the GPLv3 license applies to the whole repository unless stated otherwise (not the case). 

Check successful projects like [Linux](https://github.com/torvalds/linux/blob/master/LICENSES/preferred/GPL-2.0), they do it the same way.
