### ISSUE TITLE
Add zig as cross-compiler instead of gcc

### ISSUE THREAD

**Issue by ThanosYeah** [malwarepad/cavOS#5]
Why?

- Install simply by unzipping a tarball
You just download a tarball unzip it and here you go you have the fully fledged executable with the compiler and the language itself included,   also it saves time for users that don't have beefy machines
-Cross Compiling by deafult !
Yes cross-compiling is included out of the box
and is as simple as zig cc --target="THETARGET"
-Caching System
Caching by default
-Very small and portable 
It only weights under 45 mib compared to the huge and storage heavy gcc. Also it reduces dependecies needed because you aren't going to be cross-compiling gcc
- Build system by default
You can just have one build.zig file that will compile all of the code when running just zig build(note it might be compilcated to set up correctly)
- Implement code in zig lang for long term maintance of the codebase
You can implement or migrate parts of the code in the more safer and modern zig lang and in some cases it is faster than c
But the current system works fine...

- Yes that is true,while gcc is solid and good enough,zig would complement the average user like me of compiling the project modifying 
it refactoring,and also save some time.
Links that might be usefull

- https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html an article of show-casing what it does
- https://zig.news/kristoff/compile-a-c-c-project-with-zig-368 an article containing how to compile c projects with zig

With that said, goodluck experimenting if you want to give zig a try!

**Comment by malwarepad** [comment]
I really appreciate this suggestion but it is way, wayyy out of scope. This is a project that I run while _learning_... This means I read a lot of documentation, wiki pages and other resources while simultaneously writing code for cavOS. GCC and its cross compiling is the traditional choice for operating system developers, making it really well documented. I don't disagree that zig could have setup advantages, but it is simply easier for me to use GCC.

Apart from that, I'm extremely happy with this "old and bulky" tool since it works. And it hasn't presented any issues for larger kernels, like the Linux kernel for instance.

About the suggestions related to changing the language from C to zig, it is a clear no. I don't have any experience in this obscure codebase and honestly appreciate C for it's simplicity and predictability. I wouldn't trade it for any other language, at least for the time being.

**Comment by ThanosYeah** [comment]
Ok,thank you for reading atleast reading the suggestion, have a good day!
